package com.heater.analysis;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public final class ReadmePatcher {

    private static final Pattern MARKER_PATTERN = Pattern.compile(
            "<!-- SCALABILITY:BEGIN[^>]*-->.*?<!-- SCALABILITY:END -->",
            Pattern.DOTALL
    );

    private static final Pattern CONVECTION_PATTERN = Pattern.compile(
            "<!-- CONVECTION:BEGIN[^>]*-->.*?<!-- CONVECTION:END -->",
            Pattern.DOTALL
    );

    private static final Pattern ACOUSTIC_PATTERN = Pattern.compile(
            "<!-- ACOUSTIC:BEGIN[^>]*-->.*?<!-- ACOUSTIC:END -->",
            Pattern.DOTALL
    );

    private static final Pattern MDMG_BENCHMARK_PATTERN = Pattern.compile(
            "<!-- MDMG_BENCHMARK:BEGIN[^>]*-->.*?<!-- MDMG_BENCHMARK:END -->",
            Pattern.DOTALL
    );

    private ReadmePatcher() {}

    public static void patchMdmgBenchmark(Path readmePath, String markdown) throws IOException {
        String readme = Files.readString(readmePath);
        if (!readme.contains("<!-- MDMG_BENCHMARK:BEGIN")) {
            throw new IllegalStateException(
                    "README missing MDMG_BENCHMARK markers at " + readmePath);
        }
        String replacement = "<!-- MDMG_BENCHMARK:BEGIN — auto-generated by ./gradlew generateMdmgBenchmark; do not edit -->\n"
                + markdown.trim()
                + "\n<!-- MDMG_BENCHMARK:END -->";
        Matcher m = MDMG_BENCHMARK_PATTERN.matcher(readme);
        if (!m.find()) {
            throw new IllegalStateException("Could not match MDMG_BENCHMARK marker block in README");
        }
        String updated = m.replaceFirst(Matcher.quoteReplacement(replacement));
        Files.writeString(readmePath, updated);
    }

    public static void patchAcoustic(Path readmePath, String acousticMarkdown) throws IOException {
        String readme = Files.readString(readmePath);
        if (!readme.contains("<!-- ACOUSTIC:BEGIN")) {
            throw new IllegalStateException(
                    "README missing ACOUSTIC markers at " + readmePath);
        }
        String replacement = "<!-- ACOUSTIC:BEGIN — auto-generated by ./gradlew generateAcousticFigures; do not edit -->\n"
                + acousticMarkdown.trim()
                + "\n<!-- ACOUSTIC:END -->";
        Matcher m = ACOUSTIC_PATTERN.matcher(readme);
        if (!m.find()) {
            throw new IllegalStateException("Could not match ACOUSTIC marker block in README");
        }
        String updated = m.replaceFirst(Matcher.quoteReplacement(replacement));
        Files.writeString(readmePath, updated);
    }

    public static void patchConvection(Path readmePath, String convectionMarkdown) throws IOException {
        String readme = Files.readString(readmePath);
        if (!readme.contains("<!-- CONVECTION:BEGIN")) {
            throw new IllegalStateException(
                    "README missing CONVECTION markers at " + readmePath);
        }
        String replacement = "<!-- CONVECTION:BEGIN — auto-generated by ./gradlew generateConvectionFigures; do not edit -->\n"
                + convectionMarkdown.trim()
                + "\n<!-- CONVECTION:END -->";
        Matcher m = CONVECTION_PATTERN.matcher(readme);
        if (!m.find()) {
            throw new IllegalStateException("Could not match CONVECTION marker block in README");
        }
        String updated = m.replaceFirst(Matcher.quoteReplacement(replacement));
        Files.writeString(readmePath, updated);
    }

    public static void patch(Path readmePath, String scalabilityMarkdown) throws IOException {
        String readme = Files.readString(readmePath);
        if (!readme.contains("<!-- SCALABILITY:BEGIN")) {
            throw new IllegalStateException(
                    "README missing SCALABILITY markers at " + readmePath);
        }
        String replacement = "<!-- SCALABILITY:BEGIN — auto-generated by ./gradlew generateFigures; do not edit -->\n"
                + scalabilityMarkdown.trim()
                + "\n<!-- SCALABILITY:END -->";
        Matcher m = MARKER_PATTERN.matcher(readme);
        if (!m.find()) {
            throw new IllegalStateException("Could not match SCALABILITY marker block in README");
        }
        String updated = m.replaceFirst(Matcher.quoteReplacement(replacement));
        Files.writeString(readmePath, updated);
    }
}
